// Package docedit reads and saves one markdown document for an editor
// (ADR-0023): what may be edited, conflict detection by content hash,
// validation by the check, and a path-limited commit.
package docedit

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/bytepunx/system-flow/flai/internal/check"
	"github.com/bytepunx/system-flow/flai/internal/execx"
	"github.com/bytepunx/system-flow/flai/internal/issues"
	"github.com/bytepunx/system-flow/flai/internal/threads"
	"github.com/bytepunx/system-flow/flai/internal/workitem"
)

// Edit modes.
const (
	Full = "full" // body and front matter
	Body = "body" // flai owns the front matter
	None = "none" // not editable here
)

// Doc is a document as an editor loads it.
type Doc struct {
	Path    string `json:"path"`
	Content string `json:"content"`
	Hash    string `json:"hash"`
	Mode    string `json:"mode"`
	Reason  string `json:"reason,omitempty"` // why the mode is not full
}

// Result is a successful save.
type Result struct {
	Path        string          `json:"path"`
	Hash        string          `json:"hash"`
	Unchanged   bool            `json:"unchanged,omitempty"`
	Committed   bool            `json:"committed"`
	Commit      string          `json:"commit,omitempty"`
	CommitError string          `json:"commit_error,omitempty"` // saved; the commit did not happen
	Warnings    []check.Finding `json:"warnings"`
}

// ConflictError reports that the file changed after the editor loaded it.
type ConflictError struct {
	Path    string `json:"path"`
	Current string `json:"current"`
	Hash    string `json:"hash"`
	Diff    string `json:"diff,omitempty"` // current file against the submitted content
}

func (e *ConflictError) Error() string {
	return fmt.Sprintf("conflict: %s changed after it was loaded; load the current version or save over it", e.Path)
}

// RefusedError reports content flai will not save.
type RefusedError struct {
	Path     string          `json:"path"`
	Reason   string          `json:"reason"`
	Findings []check.Finding `json:"findings"`
}

func (e *RefusedError) Error() string { return "refused: " + e.Reason }

// SaveOptions parameterise a save.
type SaveOptions struct {
	Hash     string   // hash of the content the editor loaded
	Message  string   // commit subject after the type prefix; default "edit <path>"
	Trailers []string // lines appended to the commit message
	NoCommit bool
	Now      time.Time
}

// Hash is the identity of a document's content for conflict detection.
func Hash(content string) string {
	sum := sha256.Sum256([]byte(content))
	return hex.EncodeToString(sum[:])
}

// Resolve maps a repository path to a markdown file inside the design,
// docs, or wip folders, preferring the tree flai runs in and falling back
// to the main checkout, where wip always lives. It returns the absolute
// path and the cleaned repository path.
func Resolve(repo *workitem.Repo, rel string) (abs, clean string, err error) {
	clean = filepath.ToSlash(filepath.Clean(strings.TrimPrefix(rel, "./")))
	if clean == "." || strings.HasPrefix(clean, "../") || filepath.IsAbs(clean) || !strings.HasSuffix(clean, ".md") {
		return "", "", fmt.Errorf("%q is not a markdown path inside the repository", rel)
	}
	allowed := false
	for _, key := range []string{"design", "docs", "wip"} {
		dir := strings.TrimSuffix(repo.Manifest.Layout[key], "/")
		if dir != "" && strings.HasPrefix(clean, dir+"/") {
			allowed = true
		}
	}
	if !allowed {
		return "", "", fmt.Errorf("%q is outside the design, docs, and wip folders", rel)
	}
	for _, root := range []string{repo.Root, repo.MainRoot} {
		if root == "" {
			continue
		}
		p := filepath.Join(root, filepath.FromSlash(clean))
		if st, err := os.Stat(p); err == nil && st.Mode().IsRegular() {
			return p, clean, nil
		}
	}
	return "", "", fmt.Errorf("%s does not exist", clean)
}

// ModeOf says how much of a file an editor may change, and why not all of it.
func ModeOf(repo *workitem.Repo, abs string) (mode, reason string) {
	under := func(dir string) bool {
		rel, err := filepath.Rel(dir, abs)
		return err == nil && rel != "." && !strings.HasPrefix(rel, "..")
	}
	switch {
	case under(repo.ArchiveDir()):
		return None, "archived items and narratives are a record and are not edited"
	case under(threads.Dir(repo)):
		return None, "threads are written with replies, not edited"
	case under(issues.Dir(repo)):
		if filepath.Base(abs) == "summary.md" {
			return None, "summary.md is generated by flai issue"
		}
		return None, "issues are recorded with flai issue, which owns their counts and summary"
	case abs == filepath.Join(repo.AgentsDir(), "index.md"):
		return None, "index.md is generated from the narratives"
	case under(repo.KanbanDir()):
		if filepath.Base(abs) == "board.md" {
			return Body, "flai owns the board's limits and pull order"
		}
		return Body, "flai owns a work item's front matter; move, block, and retitle it with flai"
	case under(repo.AgentsDir()):
		return Body, "flai owns a narrative's front matter"
	}
	return Full, ""
}

// Show loads a document for editing.
func Show(repo *workitem.Repo, rel string) (*Doc, error) {
	abs, clean, err := Resolve(repo, rel)
	if err != nil {
		return nil, err
	}
	data, err := os.ReadFile(abs)
	if err != nil {
		return nil, err
	}
	mode, reason := ModeOf(repo, abs)
	return &Doc{Path: clean, Content: string(data), Hash: Hash(string(data)), Mode: mode, Reason: reason}, nil
}

var updatedLine = regexp.MustCompile(`(?m)^updated: *(\S+) *$`)
var itemID = regexp.MustCompile(`^([EST]-\d+)`)

// Save writes content to the document when the rules of ADR-0023 allow it.
// The error is a *ConflictError or a *RefusedError when that is why.
func Save(repo *workitem.Repo, r execx.Runner, rel, content string, opt SaveOptions) (*Result, error) {
	abs, clean, err := Resolve(repo, rel)
	if err != nil {
		return nil, err
	}
	if opt.Now.IsZero() {
		opt.Now = time.Now()
	}
	if !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	oldData, err := os.ReadFile(abs)
	if err != nil {
		return nil, err
	}
	old := string(oldData)
	mode, reason := ModeOf(repo, abs)
	if mode == None {
		return nil, &RefusedError{Path: clean, Reason: clean + " cannot be edited here: " + reason}
	}
	if Hash(old) != opt.Hash {
		return nil, &ConflictError{Path: clean, Current: old, Hash: Hash(old), Diff: diff(r, abs, clean, content)}
	}
	oldFM, _, oldErr := workitem.SplitFrontMatter(old)
	newFM, _, newErr := workitem.SplitFrontMatter(content)
	if mode == Body && (oldFM != newFM || (oldErr == nil) != (newErr == nil)) {
		return nil, &RefusedError{Path: clean, Reason: "the front matter of " + clean + " was changed: " + reason}
	}
	if mode == Full && oldErr == nil && newErr == nil {
		// Bump the date unless the designer set one themselves.
		today := opt.Now.UTC().Format("2006-01-02")
		if o, n := updatedLine.FindStringSubmatch(oldFM), updatedLine.FindStringSubmatch(newFM); o != nil && n != nil && o[1] == n[1] && n[1] != today {
			bumped := updatedLine.ReplaceAllString(newFM, "updated: "+today)
			content = "---\n" + bumped + strings.TrimPrefix(content, "---\n"+newFM)
		}
	}
	if content == old {
		return &Result{Path: clean, Hash: Hash(old), Unchanged: true, Warnings: []check.Finding{}}, nil
	}

	before, err := check.Run(repo, opt.Now)
	if err != nil {
		return nil, err
	}
	if err := writeAtomic(abs, content); err != nil {
		return nil, err
	}
	after, err := check.Run(repo, opt.Now)
	if err != nil {
		_ = writeAtomic(abs, old)
		return nil, err
	}
	checkPath := clean
	if p, err := filepath.Rel(repo.Root, abs); err == nil {
		checkPath = filepath.ToSlash(p)
	}
	known := map[string]bool{}
	for _, f := range before.Findings {
		known[f.Rule+"\x00"+f.Path+"\x00"+f.Message] = true
	}
	res := &Result{Path: clean, Hash: Hash(content), Warnings: []check.Finding{}}
	var blocking []check.Finding
	for _, f := range after.Findings {
		onPath := filepath.ToSlash(f.Path) == checkPath
		isNew := !known[f.Rule+"\x00"+f.Path+"\x00"+f.Message]
		// Refuse what the edit introduces, at any level: the repository's
		// gate is the strict check, and every document rule is a warning.
		// An error already on the file also refuses, until the edit fixes it.
		switch {
		case isNew || (onPath && f.Level == check.Error):
			blocking = append(blocking, f)
		case onPath:
			res.Warnings = append(res.Warnings, f)
		}
	}
	if len(blocking) > 0 {
		if err := writeAtomic(abs, old); err != nil {
			return nil, fmt.Errorf("the check refused %s and restoring it failed: %w", clean, err)
		}
		return nil, &RefusedError{Path: clean, Reason: fmt.Sprintf("flai check has %d finding(s) with this content; nothing was saved", len(blocking)), Findings: blocking}
	}

	if opt.NoCommit || !repo.Manifest.Autocommit() {
		return res, nil
	}
	root := repo.Root
	if rel, err := filepath.Rel(root, abs); err != nil || strings.HasPrefix(rel, "..") {
		root = repo.MainRoot
	}
	inRoot, _ := filepath.Rel(root, abs)
	// A failed commit is not a failed save: the file is written and valid,
	// so the result says what happened and the caller decides.
	sha, inRepo, err := commit(r, root, inRoot, commitMessage(repo, clean, opt))
	switch {
	case !inRepo:
	case err != nil:
		res.CommitError = err.Error()
	default:
		res.Committed, res.Commit = true, sha
	}
	return res, nil
}

// commit records one path on the current branch of the checkout at root.
// inRepo is false when root is not a git work tree, which is not an error.
func commit(r execx.Runner, root, path, msg string) (sha string, inRepo bool, err error) {
	if _, err := r.Run(root, "git", "rev-parse", "--is-inside-work-tree"); err != nil {
		return "", false, nil //nolint:nilerr // no repository means nothing to commit to, by design
	}
	if _, err := r.Run(root, "git", "add", "--", path); err != nil {
		return "", true, err
	}
	if _, err := r.Run(root, "git", "commit", "--quiet", "-m", msg, "--", path); err != nil {
		return "", true, err
	}
	sha, err = r.Run(root, "git", "rev-parse", "--short", "HEAD")
	return sha, true, err
}

// commitMessage follows design/conventions/git.md: docs for design and
// docs files, chore for wip, the item named when the file belongs to one.
func commitMessage(repo *workitem.Repo, clean string, opt SaveOptions) string {
	kind := "docs"
	wip := strings.TrimSuffix(repo.Manifest.Layout["wip"], "/") + "/"
	if strings.HasPrefix(clean, wip) {
		kind = "chore"
	}
	subject := strings.TrimSpace(opt.Message)
	if subject == "" {
		subject = "edit " + clean
	}
	if m := itemID.FindStringSubmatch(filepath.Base(clean)); m != nil && kind == "chore" {
		subject = "[" + m[1] + "] " + subject
	}
	msg := kind + ": " + subject
	if len(opt.Trailers) > 0 {
		msg += "\n\n" + strings.Join(opt.Trailers, "\n")
	}
	return msg
}

// diff is a unified diff of the current file against the submitted
// content, for the designer to see what they would overwrite. Best effort:
// empty without git.
func diff(r execx.Runner, abs, clean, submitted string) string {
	tmp, err := os.CreateTemp("", "flai-submitted-*.md")
	if err != nil {
		return ""
	}
	defer func() { _ = os.Remove(tmp.Name()) }()
	if _, err := tmp.WriteString(submitted); err != nil {
		return ""
	}
	_ = tmp.Close()
	// git diff --no-index exits 1 when the files differ; the output is the point.
	out, _ := r.Run("", "git", "diff", "--no-index", "--no-color", "--", abs, tmp.Name())
	// Name the two sides for the reader, and keep host paths out of it.
	var lines []string
	for _, l := range strings.Split(out, "\n") {
		switch {
		case strings.HasPrefix(l, "diff --git "), strings.HasPrefix(l, "index "):
			continue
		case strings.HasPrefix(l, "--- "):
			l = "--- " + clean + " (current)"
		case strings.HasPrefix(l, "+++ "):
			l = "+++ " + clean + " (yours)"
		}
		lines = append(lines, l)
	}
	return strings.Join(lines, "\n")
}

func writeAtomic(path, content string) error {
	st, err := os.Stat(path)
	if err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".flai-save-*")
	if err != nil {
		return err
	}
	name := tmp.Name()
	if _, err := tmp.WriteString(content); err != nil {
		_ = tmp.Close()
		_ = os.Remove(name)
		return err
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(name)
		return err
	}
	if err := os.Chmod(name, st.Mode().Perm()); err != nil {
		_ = os.Remove(name)
		return err
	}
	if err := os.Rename(name, path); err != nil {
		_ = os.Remove(name)
		return err
	}
	return nil
}

// IsConflict and IsRefused unwrap the two expected failures.
func IsConflict(err error) (*ConflictError, bool) {
	var e *ConflictError
	return e, errors.As(err, &e)
}

// IsRefused reports whether err is a refusal and returns it.
func IsRefused(err error) (*RefusedError, bool) {
	var e *RefusedError
	return e, errors.As(err, &e)
}
