package cmd

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// The dashboard token (ADR-0018): one per project, generated by flai, stored
// under .flai-cache with mode 0600, mounted read-only into the container,
// never an environment variable, argument, or log field.
const (
	tokenFileName     = "dashboard.token"
	tokenMountPath    = "/run/secrets/flaiover_token"
	tokenBytes        = 32
	tokenFileMode     = 0o600
	cacheDirName      = ".flai-cache"
	tokenFileEnv      = "FLAIOVER_TOKEN_FILE"
	tokenFragmentName = "token"
)

func tokenPath(root string) string {
	return filepath.Join(root, cacheDirName, tokenFileName)
}

// ensureToken returns the project's dashboard token, creating it when missing.
func ensureToken(root string) (token string, created bool, err error) {
	p := tokenPath(root)
	if data, err := os.ReadFile(p); err == nil && strings.TrimSpace(string(data)) != "" {
		return strings.TrimSpace(string(data)), false, nil
	}
	token, err = writeToken(root)
	return token, true, err
}

// writeToken generates a fresh token and writes it in place, so a container
// that bind-mounts the file sees the new content after a restart.
func writeToken(root string) (string, error) {
	buf := make([]byte, tokenBytes)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	token := base64.RawURLEncoding.EncodeToString(buf)
	if err := os.MkdirAll(filepath.Join(root, cacheDirName), 0o700); err != nil {
		return "", err
	}
	p := tokenPath(root)
	if err := os.WriteFile(p, []byte(token+"\n"), tokenFileMode); err != nil {
		return "", err
	}
	if err := os.Chmod(p, tokenFileMode); err != nil {
		return "", err
	}
	return token, nil
}

func loginURL(base, token string) string {
	return base + "/login#" + tokenFragmentName + "=" + token
}

// tokenArgs are the docker run arguments that hand the token to the container.
func tokenArgs(root string) []string {
	return []string{
		"--mount", "type=bind,source=" + tokenPath(root) + ",target=" + tokenMountPath + ",readonly",
		"--env", tokenFileEnv + "=" + tokenMountPath,
	}
}

func newDashboardTokenCmd(a *app) *cobra.Command {
	var rotate bool
	c := &cobra.Command{
		Use:   "token",
		Short: "Print the dashboard token and login link; --rotate replaces it",
		Long: `The token lives at .flai-cache/dashboard.token (mode 0600, git-ignored) and
is created by flai dashboard on first run. Browsers use the login link, whose
fragment never leaves the browser; agents send it as a bearer header. --rotate
writes a new token in place and restarts a running dashboard, which ends
every session.`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			repo, err := a.project()
			if err != nil {
				return err
			}
			s, err := a.dashboardSettings(repo, "", "", 0, "")
			if err != nil {
				return err
			}
			var token string
			created := false
			if rotate {
				token, err = writeToken(repo.MainRoot)
			} else {
				token, created, err = ensureToken(repo.MainRoot)
			}
			if err != nil {
				return err
			}
			restarted := false
			if rotate {
				if running, _ := a.containerRunning(s.Name); running {
					if _, err := a.runner.Run("", "docker", "restart", s.Name); err != nil {
						return err
					}
					restarted = true
				}
			}
			if a.jsonOut {
				return a.printJSON(map[string]any{"token": token, "file": relPath(repo.MainRoot, tokenPath(repo.MainRoot)), "login_url": loginURL(s.url(), token), "created": created, "rotated": rotate, "restarted": restarted})
			}
			fmt.Fprintf(a.out, "token: %s\nfile:  %s\nlogin: %s\n", token, relPath(repo.MainRoot, tokenPath(repo.MainRoot)), loginURL(s.url(), token))
			if restarted {
				fmt.Fprintf(a.out, "restarted %s; every session must log in again\n", s.Name)
			}
			return nil
		},
	}
	c.Flags().BoolVar(&rotate, "rotate", false, "replace the token and restart a running dashboard")
	return c
}
