package cmd

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// The dashboard token (ADR-0018): one per project, generated by flai, stored
// under .flai-cache with mode 0600, mounted read-only into the container,
// never an environment variable, argument, or log field.
const (
	tokenFileName     = "dashboard.token"
	tokenMountPath    = "/run/secrets/flaiover_token"
	tokenBytes        = 32
	tokenFileMode     = 0o600
	cacheDirName      = ".flai-cache"
	tokenFileEnv      = "FLAIOVER_TOKEN_FILE"
	tokenFragmentName = "token"
)

// tokenPath and agentKeyPath (dashboard_agent.go) are files in dir, which is
// always the shared serve directory beside flai's config (S-0080): one
// dashboard, one login token, one agent credential per user. A project's own
// .flai-cache no longer holds either.
func tokenPath(dir string) string { return filepath.Join(dir, tokenFileName) }

// ensureToken returns the shared dashboard token, creating it when missing.
func ensureToken(dir string) (token string, created bool, err error) {
	p := tokenPath(dir)
	if data, err := os.ReadFile(p); err == nil && strings.TrimSpace(string(data)) != "" {
		return strings.TrimSpace(string(data)), false, nil
	}
	token, err = writeToken(dir)
	return token, true, err
}

// writeToken generates a fresh token and writes it in place, so a container
// that bind-mounts the file sees the new content after a restart.
func writeToken(dir string) (string, error) {
	buf := make([]byte, tokenBytes)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	token := base64.RawURLEncoding.EncodeToString(buf)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", err
	}
	p := tokenPath(dir)
	if err := os.WriteFile(p, []byte(token+"\n"), tokenFileMode); err != nil {
		return "", err
	}
	if err := os.Chmod(p, tokenFileMode); err != nil {
		return "", err
	}
	return token, nil
}

func loginURL(base, token string) string {
	return base + "/login#" + tokenFragmentName + "=" + token
}

// tokenArgs are the docker run arguments that hand the token to the container.
func tokenArgs(dir string) []string {
	return []string{
		"--mount", "type=bind,source=" + tokenPath(dir) + ",target=" + tokenMountPath + ",readonly",
		"--env", tokenFileEnv + "=" + tokenMountPath,
	}
}

func newDashboardTokenCmd(a *app) *cobra.Command {
	var rotate bool
	c := &cobra.Command{
		Use:   "token",
		Short: "Print the dashboard token and login link; --rotate replaces it",
		Long: `One token for every project the dashboard serves (S-0080), created by flai
dashboard on first run and kept beside flai serve's state, next to flai's
config file. Browsers use the login link, whose fragment never leaves the
browser; agents send it as a bearer header. --rotate writes a new token in
place and restarts the dashboard, which ends every session, for every
project it serves, not only this one.`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			repo, err := a.project()
			if err != nil {
				return err
			}
			s, err := a.dashboardSettings(repo, "", "", 0, "")
			if err != nil {
				return err
			}
			dir := string(a.serveDir())
			var token string
			created := false
			if rotate {
				token, err = writeToken(dir)
			} else {
				token, created, err = ensureToken(dir)
			}
			if err != nil {
				return err
			}
			restarted := false
			if rotate {
				if running, _ := a.containerRunning(s.Name); running {
					if _, err := a.runner.Run("", "docker", "restart", s.Name); err != nil {
						return err
					}
					restarted = true
				}
			}
			if a.jsonOut {
				return a.printJSON(map[string]any{"token": token, "file": tokenPath(dir), "login_url": loginURL(s.url(), token), "created": created, "rotated": rotate, "restarted": restarted})
			}
			fmt.Fprintf(a.out, "token: %s\nfile:  %s\nlogin: %s\n", token, tokenPath(dir), loginURL(s.url(), token))
			if restarted {
				fmt.Fprintf(a.out, "restarted %s; every session must log in again, for every project it serves\n", s.Name)
			}
			return nil
		},
	}
	c.Flags().BoolVar(&rotate, "rotate", false, "replace the token and restart the dashboard, for every project it serves")
	return c
}
