package cmd

import (
	"fmt"
	"os"
	"regexp"
	"strings"

	"github.com/spf13/cobra"

	"github.com/bytepunx/system-flow/flai/internal/issues"
	"github.com/bytepunx/system-flow/flai/internal/itemnew"
	"github.com/bytepunx/system-flow/flai/internal/storygit"
	"github.com/bytepunx/system-flow/flai/internal/workitem"
)

func newIssueCmd(a *app) *cobra.Command {
	c := &cobra.Command{
		Use:   "issue",
		Short: "Record recurring friction in design/issues with counts and cost",
		Long: `Issues are the continuous-improvement record: one file per recurring
problem with a class (` + strings.Join(issues.Classes, ", ") + `), a count, an average
cost per occurrence, and the instances. summary.md is regenerated by every
command here.`,
	}
	c.AddCommand(newIssueNewCmd(a), newIssueBumpCmd(a), newIssueCloseCmd(a), newIssueSummaryCmd(a), newIssueListCmd(a), newIssueStoryCmd(a))
	return c
}

var (
	agentStoryRe  = regexp.MustCompile(`^agent-(S-\d+)$`)
	branchStoryRe = regexp.MustCompile(`^` + regexp.QuoteMeta(storygit.Prefix) + `(S-\d+)$`)
)

// storyHelp is the --story flag's help for issue new and bump.
const storyHelp = "the story this occurrence belongs to (default: FLAI_STORY, else the story in FLAI_AGENT of the form agent-S-nnnn, else the story branch checked out here)"

// recordingStory is the story an occurrence is recorded for: the flag, else
// FLAI_STORY, else the S-nnnn in FLAI_AGENT of the form agent-S-nnnn, else
// the story whose branch, story/S-nnnn, is checked out. Empty is none.
func recordingStory(flag string, getenv func(string) string, branch func() string) string {
	if s := strings.TrimSpace(flag); s != "" {
		return s
	}
	if s := strings.TrimSpace(getenv("FLAI_STORY")); s != "" {
		return s
	}
	if m := agentStoryRe.FindStringSubmatch(strings.TrimSpace(getenv("FLAI_AGENT"))); m != nil {
		return m[1]
	}
	if m := branchStoryRe.FindStringSubmatch(branch()); m != nil {
		return m[1]
	}
	return ""
}

// issueStory resolves recordingStory with the process environment and the
// branch checked out at the project root; a project not in git has none.
func (a *app) issueStory(repo *workitem.Repo, flag string) string {
	return recordingStory(flag, os.Getenv, func() string {
		out, err := a.runner.Run(repo.Root, "git", "rev-parse", "--abbrev-ref", "HEAD")
		if err != nil {
			return ""
		}
		return strings.TrimSpace(out)
	})
}

func (a *app) refreshSummary() ([]*issues.Issue, error) {
	repo, err := a.project()
	if err != nil {
		return nil, err
	}
	return issues.WriteSummary(repo, a.now())
}

// issueImpactFlags adds the flags that give an issue's Impact section, and
// the report that found it, to issue new and bump (S-0224).
func issueImpactFlags(c *cobra.Command, im *issues.Impact, report *string) {
	c.Flags().StringVar(&im.RevenuePerWeek, "revenue-per-week", "", "Impact: the revenue lost each week it stays open, an amount of zero or more in planning.currency")
	c.Flags().StringVar(&im.PenaltyPerWeek, "penalty-per-week", "", "Impact: the penalty paid each week it stays open, an amount of zero or more in planning.currency")
	c.Flags().StringVar(&im.TimeLostPerCycle, "time-lost-per-cycle", "", "Impact: the time it loses each planning cycle, a duration longer than zero, e.g. 4h")
	c.Flags().StringVar(&im.Evidence, "evidence", "", "Impact: the evidence for the figures, in any words")
	c.Flags().StringVar(report, "report", "", "the analysis report under design/analysis that found it, from the project root; the instance names it and the Remediation section links it")
}

// issueFiled is an issue as flai issue new --report --json gives it: with
// whether it was opened, bumped, or already recorded from the report.
type issueFiled struct {
	*issues.Issue
	Outcome issues.Outcome `json:"outcome"`
}

// issueCommitFlags adds --commit and --trailer to issue new, bump, and close
// (S-0275).
func issueCommitFlags(c *cobra.Command, commit *bool, trailers *[]string) {
	c.Flags().BoolVar(commit, "commit", false, commitFlagHelp)
	c.Flags().StringArrayVar(trailers, "trailer", nil, "trailer line for the --commit commit (repeatable)")
}

// issueCommitHelp is what --commit does, for the Long help of issue new,
// bump, and close.
const issueCommitHelp = `--commit, run in a story's worktree, commits what was written, the issue's
file and summary.md, and nothing else, on the story's branch as
"docs: [S-nnnn] %s I-nnnn <title>", with each --trailer, and adds them to the
story's touches in the main checkout. The output then says what was committed and what the
touches gained; --json adds commit (null when nothing changed) and
touches_added. Where the story's branch is not checked out, or no story
resolves, --commit is refused and nothing is written.`

// printIssueJSON prints an issue as --json gives it, with what --commit did
// when it was given; outcome is printed when withOutcome.
func (a *app) printIssueJSON(is *issues.Issue, outcome issues.Outcome, withOutcome bool, done *storyCommitted) error {
	if done == nil {
		if withOutcome {
			return a.printJSON(issueFiled{Issue: is, Outcome: outcome})
		}
		return a.printJSON(is)
	}
	out := issueCommitted{Issue: is, Commit: done.commit, TouchesAdded: done.touches.Story}
	if withOutcome {
		out.Outcome = outcome
	}
	return a.printJSON(out)
}

// commitIssue commits what an issue command wrote, when --commit was given,
// as "<verb> I-nnnn <title>"; nil when it was not.
func (a *app) commitIssue(sc *storyCommit, repo *workitem.Repo, is *issues.Issue, verb string) (*storyCommitted, error) {
	if sc == nil {
		return nil, nil
	}
	paths, err := issueWritten(repo, is)
	if err != nil {
		return nil, err
	}
	done, err := a.commitForStory(sc, verb+" "+is.ID+" "+is.Title, paths)
	if err != nil {
		return nil, err
	}
	return &done, nil
}

// beginIssueCommit is beginStoryCommit for an issue command, nil when
// --commit was not given.
func (a *app) beginIssueCommit(repo *workitem.Repo, commit bool, story string, trailers []string) (*storyCommit, error) {
	if !commit {
		return nil, nil
	}
	return a.beginStoryCommit(repo, story, false, trailers)
}

func newIssueNewCmd(a *app) *cobra.Command {
	var class, cost, note, story, report string
	var impact issues.Impact
	var commit bool
	var trailers []string
	c := &cobra.Command{
		Use:   "new \"<title>\"",
		Short: "Record a new issue (count 1), or a report's finding",
		Long: `Record a new issue with count 1. Its number is one past the highest issue
on main, in any story worktree, and on any story branch, so stories worked
in parallel do not take the same number.

--revenue-per-week, --penalty-per-week, and --time-lost-per-cycle give what
it costs while it stays open, and --evidence the words behind them: the issue
gets an Impact section, one "- key: value" line per figure after the
evidence, which flai issue story carries over as the cost of delay inputs of
the story it makes. An amount is a number of zero or more, a duration a Go
duration longer than zero; anything else is refused and nothing is written.

--report names the analysis report under design/analysis that found it (the
analyzer's finding). The instance says "Report: <path>." and the Remediation
section links the report. With --report an open issue of the same title is
bumped, with the report, impact, and note, rather than a second one opened,
and left as it is when an instance already names that report; the output
says which happened, and --json gives it as outcome: opened, bumped, or
already recorded. A path that is not a markdown file under design/analysis is
refused and nothing is written.

` + fmt.Sprintf(issueCommitHelp, "record") + ` A bumped issue's
commit says bump; one already recorded from the report commits nothing.`,
		Example: `  flai issue new "golangci-lint on the host is v1 but the config is v2" --class efficiency --cost 5m
  flai issue new "Fixture under bin/ was git-ignored" --class defect --cost 15m --note "found by the release dry run"
  flai issue new "Review waits a day for the operator" --class efficiency --time-lost-per-cycle 6h \
    --evidence "12 stories waited 18h on average in review" --report design/analysis/2026-10-06-bottlenecks.md --json
  flai issue new "The lint cache is shared between worktrees" --class defect --cost 10m --commit \
    --trailer "Co-Authored-By: Claude <noreply@anthropic.com>"`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			repo, err := a.project()
			if err != nil {
				return err
			}
			sc, err := a.beginIssueCommit(repo, commit, story, trailers)
			if err != nil {
				return err
			}
			is, outcome, err := issues.NewOrBump(repo, issues.NewOptions{Title: args[0], Class: class, Cost: cost, Note: note, Story: a.issueStory(repo, story),
				Impact: impact, Report: report, Now: a.now(), Runner: a.runner})
			if err != nil {
				return err
			}
			if _, err := issues.WriteSummary(repo, a.now()); err != nil {
				return err
			}
			verb := "record"
			if outcome == issues.Bumped {
				verb = "bump"
			}
			done, err := a.commitIssue(sc, repo, is, verb)
			if err != nil {
				return err
			}
			if a.jsonOut {
				return a.printIssueJSON(is, outcome, report != "", done)
			}
			fmt.Fprintf(a.out, "%s %s\n  %s\n", is.ID, is.Title, relPath(repo.Root, is.Path))
			if report != "" {
				switch outcome {
				case issues.Bumped:
					fmt.Fprintf(a.out, "  bumped the open issue of this title, count %d\n", is.Count)
				case issues.Already:
					fmt.Fprintln(a.out, "  already recorded from this report; nothing changed")
				default:
					fmt.Fprintln(a.out, "  opened")
				}
			}
			if done != nil {
				done.print(a)
			}
			return nil
		},
	}
	c.Flags().StringVar(&class, "class", "", "one of "+strings.Join(issues.Classes, ", "))
	c.Flags().StringVar(&cost, "cost", "", "wall-clock cost of this occurrence, e.g. 20m")
	c.Flags().StringVar(&note, "note", "", "what happened, recorded as the first instance")
	c.Flags().StringVar(&story, "story", "", storyHelp)
	issueImpactFlags(c, &impact, &report)
	issueCommitFlags(c, &commit, &trailers)
	_ = c.MarkFlagRequired("class")
	return c
}

func newIssueBumpCmd(a *app) *cobra.Command {
	var cost, note, story, report string
	var impact issues.Impact
	var commit bool
	var trailers []string
	c := &cobra.Command{
		Use:   "bump <id>",
		Short: "Record another occurrence of an issue",
		Long: `Record another occurrence of an issue: its count, last reported, average
cost, and an instance naming the story it belongs to.

--revenue-per-week, --penalty-per-week, and --time-lost-per-cycle replace
those figures in the issue's Impact section, which is added when it has none,
and keep the others; --evidence adds the words behind them. --report links
the analysis report under design/analysis that found it, as flai issue new
--report does, for a finding the analyzer judged the same as this issue under
another title. A bad amount, duration, or report path is refused and nothing
is written.

` + fmt.Sprintf(issueCommitHelp, "bump"),
		Example: `  flai issue bump I-0007 --cost 10m --note "again in the release dry run"
  flai issue bump I-0007 --report design/analysis/2026-10-06-risk.md --penalty-per-week 300 --evidence "two releases slipped"
  flai issue bump I-0007 --cost 5m --note "again while closing the story out" --commit --json`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			repo, err := a.project()
			if err != nil {
				return err
			}
			sc, err := a.beginIssueCommit(repo, commit, story, trailers)
			if err != nil {
				return err
			}
			is, err := issues.Get(repo, args[0])
			if err != nil {
				return err
			}
			if err := issues.BumpWith(repo, is, issues.BumpOptions{Story: a.issueStory(repo, story), Cost: cost, Note: note, Impact: impact, Report: report, Now: a.now()}); err != nil {
				return err
			}
			if _, err := issues.WriteSummary(repo, a.now()); err != nil {
				return err
			}
			done, err := a.commitIssue(sc, repo, is, "bump")
			if err != nil {
				return err
			}
			if a.jsonOut {
				return a.printIssueJSON(is, "", false, done)
			}
			fmt.Fprintf(a.out, "%s count %d, avg cost %s\n", is.ID, is.Count, orDefault(is.Cost, "-"))
			if done != nil {
				done.print(a)
			}
			return nil
		},
	}
	c.Flags().StringVar(&cost, "cost", "", "wall-clock cost of this occurrence; the average is updated")
	c.Flags().StringVar(&note, "note", "", "what happened this time")
	c.Flags().StringVar(&story, "story", "", storyHelp)
	issueImpactFlags(c, &impact, &report)
	issueCommitFlags(c, &commit, &trailers)
	return c
}

func newIssueCloseCmd(a *app) *cobra.Command {
	var reason string
	var commit bool
	var trailers []string
	c := &cobra.Command{
		Use:   "close <id>",
		Short: "Close an issue with a reason",
		Long: `Close an issue: its status is closed and its body ends with the reason.

` + fmt.Sprintf(issueCommitHelp, "close") + ` The story is
FLAI_STORY, else the one in FLAI_AGENT of the form agent-S-nnnn, else the
story branch checked out.`,
		Example: `  flai issue close I-0007 --reason "fixed by S-0275"
  flai issue close I-0007 --reason "fixed by S-0275" --commit`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			repo, err := a.project()
			if err != nil {
				return err
			}
			sc, err := a.beginIssueCommit(repo, commit, "", trailers)
			if err != nil {
				return err
			}
			is, err := issues.Get(repo, args[0])
			if err != nil {
				return err
			}
			if err := issues.Close(is, reason, a.now()); err != nil {
				return err
			}
			if _, err := issues.WriteSummary(repo, a.now()); err != nil {
				return err
			}
			done, err := a.commitIssue(sc, repo, is, "close")
			if err != nil {
				return err
			}
			if a.jsonOut {
				return a.printIssueJSON(is, "", false, done)
			}
			fmt.Fprintf(a.out, "%s closed\n", is.ID)
			if done != nil {
				done.print(a)
			}
			return nil
		},
	}
	c.Flags().StringVar(&reason, "reason", "", "what closed it (a story ID, a fix, or why it no longer applies)")
	issueCommitFlags(c, &commit, &trailers)
	_ = c.MarkFlagRequired("reason")
	return c
}

func newIssueSummaryCmd(a *app) *cobra.Command {
	return &cobra.Command{
		Use:   "summary",
		Short: "Regenerate summary.md and print the open issues table",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			list, err := a.refreshSummary()
			if err != nil {
				return err
			}
			if a.jsonOut {
				return a.printJSON(list)
			}
			table := issues.SummaryTable(list)
			if table == "" {
				fmt.Fprintln(a.out, "no open issues")
				return nil
			}
			fmt.Fprint(a.out, table)
			return nil
		},
	}
}

func newIssueListCmd(a *app) *cobra.Command {
	var all bool
	var story string
	c := &cobra.Command{
		Use:   "list",
		Short: "List issues without touching files",
		Long: `List issues without touching files. --story lists only the issues with an
occurrence recorded for that story, read from the story's worktree when it has
one: the issues a story records are committed on its branch and are there
until it is accepted. --json gives every issue, closed ones too, with stories,
the stories its occurrences name, and story, the open story that links it, or
"" when none does.`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			repo, err := a.project()
			if err != nil {
				return err
			}
			list, err := issues.List(issues.RepoFor(repo, story))
			if err != nil {
				return err
			}
			if story != "" {
				list = issues.RecordedBy(list, story)
			}
			if a.jsonOut {
				items, err := repo.List(false)
				if err != nil {
					return err
				}
				out := make([]issueListed, 0, len(list))
				for _, is := range list {
					out = append(out, issueListed{Issue: is, Stories: append([]string{}, issues.Stories(is)...), Story: issues.LinkedBy(is, items)})
				}
				return a.printJSON(out)
			}
			for _, is := range list {
				if !all && is.Status != "open" {
					continue
				}
				fmt.Fprintf(a.out, "%-6s %-11s %-7s %3d  %-5s %s\n", is.ID, is.Class, is.Status, is.Count, orDefault(is.Cost, "-"), is.Title)
			}
			return nil
		},
	}
	c.Flags().BoolVar(&all, "all", false, "include closed issues")
	c.Flags().StringVar(&story, "story", "", "list only the issues with an occurrence recorded for this story, from its worktree when it has one")
	return c
}

// issueListed is an issue as flai issue list --json gives it.
type issueListed struct {
	*issues.Issue
	Stories []string `json:"stories"`
	Story   string   `json:"story"`
}

// issueStoryMade is the story flai issue story --json says it made.
type issueStoryMade struct {
	ID          string                `json:"id"`
	Title       string                `json:"title"`
	Nature      string                `json:"nature"`
	Path        string                `json:"path"`
	Issue       string                `json:"issue"`
	Draft       bool                  `json:"draft"`
	CostOfDelay *workitem.CostOfDelay `json:"cost_of_delay,omitempty"`
	Committed   bool                  `json:"committed"`
	Commit      string                `json:"commit,omitempty"`
	CommitError string                `json:"commit_error,omitempty"`
}

func newIssueStoryCmd(a *app) *cobra.Command {
	var epic, story, owner string
	var trailers []string
	var autocommit bool
	c := &cobra.Command{
		Use:   "story <id>",
		Short: "Make a backlog story that remediates an open issue",
		Long: `Make a backlog story from an open issue, as flai story new --body-stdin
makes one. It takes the issue's title. Its nature is remediation for a defect
or a blocker, improvement otherwise. Its goal links the issue and carries the
issue's recommended solution; that link is what ties the issue to the story.
The story is a draft: the operator finalizes it before it can be ready. When
the issue gives them, it carries the issue's cost of delay inputs, set by
flai: time_lost_per_cycle from the issue's cost and count over the planning
cycles since it was first reported, and the figures its Impact section gives,
which take precedence; its Notes say how each was set. What strategic agents
spent on the issue, its usage's strategic entries, is charged to the story
and its epic, and its Notes say so; the issue keeps its own. The issue's
Remediation section then names the story. flai check runs with the story in
place and refuses it, leaving nothing, if it reports anything the story
introduces (exit 4). A closed issue, or one an open story already links, is
refused and nothing changes. --story reads the issue from that story's
worktree, where the issues it recorded are until it is accepted, and names the
story in the issue there, for that story to commit; the new story is made in
wip/ as always. --autocommit commits the new story, its epic, and the issue
it names on their own, unless the project sets dashboard.autocommit: false.
Nothing is pushed.`,
		Example: `  flai issue story I-0007
  flai issue story I-0007 --epic E-0002 --autocommit
  flai issue story I-0012 --story S-0198`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			repo, err := a.project()
			if err != nil {
				return err
			}
			cycle, err := repo.Manifest.Planning.CycleDuration()
			if err != nil {
				return fmt.Errorf("making a story for %s: %w", args[0], err)
			}
			src := issues.RepoFor(repo, story)
			is, err := issues.Get(src, args[0])
			if err != nil {
				return err
			}
			if is.Status != "open" {
				return fmt.Errorf("%s is %s, so no story was made for it; reopen it by editing its status, or record a new issue", is.ID, is.Status)
			}
			items, err := repo.List(false)
			if err != nil {
				return err
			}
			if id := issues.LinkedBy(is, items); id != "" {
				return fmt.Errorf("%s is already linked by open story %s, so no story was made for it; work it in %s, or cancel %s first", is.ID, id, id, id)
			}
			now := a.now()
			draft := issues.ForStory(is, now, cycle)
			res, err := itemnew.Create(repo, a.runner, itemnew.Options{New: workitem.NewOptions{
				Type: workitem.Story, Title: draft.Title, Nature: draft.Nature, Parent: epic,
				Owner: orDefault(owner, a.author()), Body: draft.Body, Now: now,
				Draft: draft.Draft, CostOfDelay: draft.CostOfDelay,
			}, Autocommit: autocommit, Trailers: trailers, Then: func(it *workitem.Item) ([]string, error) {
				// the charge changes the story and its epic, both committed with it
				if _, err := issues.CarryStrategic(repo, it.ID, draft.Strategic); err != nil {
					return nil, fmt.Errorf("carrying %s's strategic usage to it: %w", is.ID, err)
				}
				if err := issues.LinkStory(is, it.ID, now); err != nil {
					return nil, fmt.Errorf("naming it in %s's Remediation section: %w", is.ID, err)
				}
				// an issue in another story's worktree is that story's to commit
				if src.Root != repo.Root {
					return nil, nil
				}
				return []string{is.Path}, nil
			}})
			if refusal, ok := a.refusedADR(err); ok {
				return refusal
			}
			if err != nil {
				return fmt.Errorf("making a story for %s: %w", is.ID, err)
			}
			if a.jsonOut {
				return a.printJSON(issueStoryMade{ID: res.Item.ID, Title: res.Item.Title, Nature: res.Item.Nature, Path: res.Path, Issue: is.ID,
					Draft: res.Item.Draft, CostOfDelay: res.Item.CostOfDelay,
					Committed: res.Committed, Commit: res.Commit, CommitError: res.CommitError})
			}
			fmt.Fprintf(a.out, "%s %s\n  %s\n", res.Item.ID, res.Item.Title, res.Path)
			switch {
			case res.Committed:
				fmt.Fprintf(a.out, "  committed %s\n", res.Commit)
			case res.CommitError != "":
				fmt.Fprintf(a.out, "  NOT committed (%s)\n", firstLine(res.CommitError))
			}
			return nil
		},
	}
	c.Flags().StringVar(&epic, "epic", "", "parent epic ID (optional: a story need not belong to one)")
	c.Flags().StringVar(&story, "story", "", "read the issue from this story's worktree when it has one")
	c.Flags().StringVar(&owner, "owner", "", "owner (default: config author)")
	c.Flags().BoolVar(&autocommit, "autocommit", false, "commit the new story, its epic, and the issue it names on their own, unless dashboard.autocommit is false")
	c.Flags().StringArrayVar(&trailers, "trailer", nil, "trailer line for the commit (repeatable)")
	return c
}
