package cmd

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	"github.com/bytepunx/system-flow/flai/internal/issues"
)

func newIssueCmd(a *app) *cobra.Command {
	c := &cobra.Command{
		Use:   "issue",
		Short: "Record recurring friction in design/issues with counts and cost",
		Long: `Issues are the continuous-improvement record: one file per recurring
problem with a class (` + strings.Join(issues.Classes, ", ") + `), a count, an average
cost per occurrence, and the instances. summary.md is regenerated by every
command here.`,
	}
	c.AddCommand(newIssueNewCmd(a), newIssueBumpCmd(a), newIssueCloseCmd(a), newIssueSummaryCmd(a), newIssueListCmd(a))
	return c
}

func (a *app) refreshSummary() ([]*issues.Issue, error) {
	repo, err := a.project()
	if err != nil {
		return nil, err
	}
	return issues.WriteSummary(repo, a.now())
}

func newIssueNewCmd(a *app) *cobra.Command {
	var class, cost, note string
	c := &cobra.Command{
		Use:   "new \"<title>\"",
		Short: "Record a new issue (count 1)",
		Example: `  flai issue new "golangci-lint on the host is v1 but the config is v2" --class efficiency --cost 5m
  flai issue new "Fixture under bin/ was git-ignored" --class defect --cost 15m --note "found by the release dry run"`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			repo, err := a.project()
			if err != nil {
				return err
			}
			is, err := issues.New(repo, issues.NewOptions{Title: args[0], Class: class, Cost: cost, Note: note, Now: a.now()})
			if err != nil {
				return err
			}
			if _, err := issues.WriteSummary(repo, a.now()); err != nil {
				return err
			}
			if a.jsonOut {
				return a.printJSON(is)
			}
			fmt.Fprintf(a.out, "%s %s\n  %s\n", is.ID, is.Title, relPath(repo.Root, is.Path))
			return nil
		},
	}
	c.Flags().StringVar(&class, "class", "", "one of "+strings.Join(issues.Classes, ", "))
	c.Flags().StringVar(&cost, "cost", "", "wall-clock cost of this occurrence, e.g. 20m")
	c.Flags().StringVar(&note, "note", "", "what happened, recorded as the first instance")
	_ = c.MarkFlagRequired("class")
	return c
}

func newIssueBumpCmd(a *app) *cobra.Command {
	var cost, note string
	c := &cobra.Command{
		Use:   "bump <id>",
		Short: "Record another occurrence of an issue",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			repo, err := a.project()
			if err != nil {
				return err
			}
			is, err := issues.Get(repo, args[0])
			if err != nil {
				return err
			}
			if err := issues.Bump(is, cost, note, a.now()); err != nil {
				return err
			}
			if _, err := issues.WriteSummary(repo, a.now()); err != nil {
				return err
			}
			if a.jsonOut {
				return a.printJSON(is)
			}
			fmt.Fprintf(a.out, "%s count %d, avg cost %s\n", is.ID, is.Count, orDefault(is.Cost, "-"))
			return nil
		},
	}
	c.Flags().StringVar(&cost, "cost", "", "wall-clock cost of this occurrence; the average is updated")
	c.Flags().StringVar(&note, "note", "", "what happened this time")
	return c
}

func newIssueCloseCmd(a *app) *cobra.Command {
	var reason string
	c := &cobra.Command{
		Use:   "close <id>",
		Short: "Close an issue with a reason",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			repo, err := a.project()
			if err != nil {
				return err
			}
			is, err := issues.Get(repo, args[0])
			if err != nil {
				return err
			}
			if err := issues.Close(is, reason, a.now()); err != nil {
				return err
			}
			if _, err := issues.WriteSummary(repo, a.now()); err != nil {
				return err
			}
			if a.jsonOut {
				return a.printJSON(is)
			}
			fmt.Fprintf(a.out, "%s closed\n", is.ID)
			return nil
		},
	}
	c.Flags().StringVar(&reason, "reason", "", "what closed it (a story ID, a fix, or why it no longer applies)")
	_ = c.MarkFlagRequired("reason")
	return c
}

func newIssueSummaryCmd(a *app) *cobra.Command {
	return &cobra.Command{
		Use:   "summary",
		Short: "Regenerate summary.md and print the open issues table",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			list, err := a.refreshSummary()
			if err != nil {
				return err
			}
			if a.jsonOut {
				return a.printJSON(list)
			}
			table := issues.SummaryTable(list)
			if table == "" {
				fmt.Fprintln(a.out, "no open issues")
				return nil
			}
			fmt.Fprint(a.out, table)
			return nil
		},
	}
}

func newIssueListCmd(a *app) *cobra.Command {
	var all bool
	c := &cobra.Command{
		Use:   "list",
		Short: "List issues without touching files",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			repo, err := a.project()
			if err != nil {
				return err
			}
			list, err := issues.List(repo)
			if err != nil {
				return err
			}
			if a.jsonOut {
				return a.printJSON(list)
			}
			for _, is := range list {
				if !all && is.Status != "open" {
					continue
				}
				fmt.Fprintf(a.out, "%-6s %-11s %-7s %3d  %-5s %s\n", is.ID, is.Class, is.Status, is.Count, orDefault(is.Cost, "-"), is.Title)
			}
			return nil
		},
	}
	c.Flags().BoolVar(&all, "all", false, "include closed issues")
	return c
}
