package cmd

import (
	"fmt"
	"os"
	"regexp"
	"strings"

	"github.com/spf13/cobra"

	"github.com/bytepunx/system-flow/flai/internal/issues"
	"github.com/bytepunx/system-flow/flai/internal/itemnew"
	"github.com/bytepunx/system-flow/flai/internal/storygit"
	"github.com/bytepunx/system-flow/flai/internal/workitem"
)

func newIssueCmd(a *app) *cobra.Command {
	c := &cobra.Command{
		Use:   "issue",
		Short: "Record recurring friction in design/issues with counts and cost",
		Long: `Issues are the continuous-improvement record: one file per recurring
problem with a class (` + strings.Join(issues.Classes, ", ") + `), a count, an average
cost per occurrence, and the instances. summary.md is regenerated by every
command here.`,
	}
	c.AddCommand(newIssueNewCmd(a), newIssueBumpCmd(a), newIssueCloseCmd(a), newIssueSummaryCmd(a), newIssueListCmd(a), newIssueStoryCmd(a))
	return c
}

var (
	agentStoryRe  = regexp.MustCompile(`^agent-(S-\d+)$`)
	branchStoryRe = regexp.MustCompile(`^` + regexp.QuoteMeta(storygit.Prefix) + `(S-\d+)$`)
)

// storyHelp is the --story flag's help for issue new and bump.
const storyHelp = "the story this occurrence belongs to (default: FLAI_STORY, else the story in FLAI_AGENT of the form agent-S-nnnn, else the story branch checked out here)"

// recordingStory is the story an occurrence is recorded for: the flag, else
// FLAI_STORY, else the S-nnnn in FLAI_AGENT of the form agent-S-nnnn, else
// the story whose branch, story/S-nnnn, is checked out. Empty is none.
func recordingStory(flag string, getenv func(string) string, branch func() string) string {
	if s := strings.TrimSpace(flag); s != "" {
		return s
	}
	if s := strings.TrimSpace(getenv("FLAI_STORY")); s != "" {
		return s
	}
	if m := agentStoryRe.FindStringSubmatch(strings.TrimSpace(getenv("FLAI_AGENT"))); m != nil {
		return m[1]
	}
	if m := branchStoryRe.FindStringSubmatch(branch()); m != nil {
		return m[1]
	}
	return ""
}

// issueStory resolves recordingStory with the process environment and the
// branch checked out at the project root; a project not in git has none.
func (a *app) issueStory(repo *workitem.Repo, flag string) string {
	return recordingStory(flag, os.Getenv, func() string {
		out, err := a.runner.Run(repo.Root, "git", "rev-parse", "--abbrev-ref", "HEAD")
		if err != nil {
			return ""
		}
		return strings.TrimSpace(out)
	})
}

func (a *app) refreshSummary() ([]*issues.Issue, error) {
	repo, err := a.project()
	if err != nil {
		return nil, err
	}
	return issues.WriteSummary(repo, a.now())
}

func newIssueNewCmd(a *app) *cobra.Command {
	var class, cost, note, story string
	c := &cobra.Command{
		Use:   "new \"<title>\"",
		Short: "Record a new issue (count 1)",
		Example: `  flai issue new "golangci-lint on the host is v1 but the config is v2" --class efficiency --cost 5m
  flai issue new "Fixture under bin/ was git-ignored" --class defect --cost 15m --note "found by the release dry run"`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			repo, err := a.project()
			if err != nil {
				return err
			}
			is, err := issues.New(repo, issues.NewOptions{Title: args[0], Class: class, Cost: cost, Note: note, Story: a.issueStory(repo, story), Now: a.now()})
			if err != nil {
				return err
			}
			if _, err := issues.WriteSummary(repo, a.now()); err != nil {
				return err
			}
			if a.jsonOut {
				return a.printJSON(is)
			}
			fmt.Fprintf(a.out, "%s %s\n  %s\n", is.ID, is.Title, relPath(repo.Root, is.Path))
			return nil
		},
	}
	c.Flags().StringVar(&class, "class", "", "one of "+strings.Join(issues.Classes, ", "))
	c.Flags().StringVar(&cost, "cost", "", "wall-clock cost of this occurrence, e.g. 20m")
	c.Flags().StringVar(&note, "note", "", "what happened, recorded as the first instance")
	c.Flags().StringVar(&story, "story", "", storyHelp)
	_ = c.MarkFlagRequired("class")
	return c
}

func newIssueBumpCmd(a *app) *cobra.Command {
	var cost, note, story string
	c := &cobra.Command{
		Use:   "bump <id>",
		Short: "Record another occurrence of an issue",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			repo, err := a.project()
			if err != nil {
				return err
			}
			is, err := issues.Get(repo, args[0])
			if err != nil {
				return err
			}
			if err := issues.Bump(is, a.issueStory(repo, story), cost, note, a.now()); err != nil {
				return err
			}
			if _, err := issues.WriteSummary(repo, a.now()); err != nil {
				return err
			}
			if a.jsonOut {
				return a.printJSON(is)
			}
			fmt.Fprintf(a.out, "%s count %d, avg cost %s\n", is.ID, is.Count, orDefault(is.Cost, "-"))
			return nil
		},
	}
	c.Flags().StringVar(&cost, "cost", "", "wall-clock cost of this occurrence; the average is updated")
	c.Flags().StringVar(&note, "note", "", "what happened this time")
	c.Flags().StringVar(&story, "story", "", storyHelp)
	return c
}

func newIssueCloseCmd(a *app) *cobra.Command {
	var reason string
	c := &cobra.Command{
		Use:   "close <id>",
		Short: "Close an issue with a reason",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			repo, err := a.project()
			if err != nil {
				return err
			}
			is, err := issues.Get(repo, args[0])
			if err != nil {
				return err
			}
			if err := issues.Close(is, reason, a.now()); err != nil {
				return err
			}
			if _, err := issues.WriteSummary(repo, a.now()); err != nil {
				return err
			}
			if a.jsonOut {
				return a.printJSON(is)
			}
			fmt.Fprintf(a.out, "%s closed\n", is.ID)
			return nil
		},
	}
	c.Flags().StringVar(&reason, "reason", "", "what closed it (a story ID, a fix, or why it no longer applies)")
	_ = c.MarkFlagRequired("reason")
	return c
}

func newIssueSummaryCmd(a *app) *cobra.Command {
	return &cobra.Command{
		Use:   "summary",
		Short: "Regenerate summary.md and print the open issues table",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			list, err := a.refreshSummary()
			if err != nil {
				return err
			}
			if a.jsonOut {
				return a.printJSON(list)
			}
			table := issues.SummaryTable(list)
			if table == "" {
				fmt.Fprintln(a.out, "no open issues")
				return nil
			}
			fmt.Fprint(a.out, table)
			return nil
		},
	}
}

func newIssueListCmd(a *app) *cobra.Command {
	var all bool
	var story string
	c := &cobra.Command{
		Use:   "list",
		Short: "List issues without touching files",
		Long: `List issues without touching files. --story lists only the issues with an
occurrence recorded for that story, read from the story's worktree when it has
one: the issues a story records are committed on its branch and are there
until it is accepted. --json gives every issue, closed ones too, with stories,
the stories its occurrences name, and story, the open story that links it, or
"" when none does.`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			repo, err := a.project()
			if err != nil {
				return err
			}
			list, err := issues.List(issues.RepoFor(repo, story))
			if err != nil {
				return err
			}
			if story != "" {
				list = issues.RecordedBy(list, story)
			}
			if a.jsonOut {
				items, err := repo.List(false)
				if err != nil {
					return err
				}
				out := make([]issueListed, 0, len(list))
				for _, is := range list {
					out = append(out, issueListed{Issue: is, Stories: append([]string{}, issues.Stories(is)...), Story: issues.LinkedBy(is, items)})
				}
				return a.printJSON(out)
			}
			for _, is := range list {
				if !all && is.Status != "open" {
					continue
				}
				fmt.Fprintf(a.out, "%-6s %-11s %-7s %3d  %-5s %s\n", is.ID, is.Class, is.Status, is.Count, orDefault(is.Cost, "-"), is.Title)
			}
			return nil
		},
	}
	c.Flags().BoolVar(&all, "all", false, "include closed issues")
	c.Flags().StringVar(&story, "story", "", "list only the issues with an occurrence recorded for this story, from its worktree when it has one")
	return c
}

// issueListed is an issue as flai issue list --json gives it.
type issueListed struct {
	*issues.Issue
	Stories []string `json:"stories"`
	Story   string   `json:"story"`
}

func newIssueStoryCmd(a *app) *cobra.Command {
	var epic, story string
	c := &cobra.Command{
		Use:   "story <id>",
		Short: "Make a backlog story that remediates an open issue",
		Long: `Make a backlog story from an open issue, as flai story new --body-stdin
makes one. It takes the issue's title. Its nature is remediation for a defect
or a blocker, improvement otherwise. Its goal links the issue and carries the
issue's recommended solution; that link is what ties the issue to the story,
and the issue's file is not changed. flai check runs with the story in place
and refuses it, leaving nothing, if it reports anything the story introduces
(exit 4). A closed issue, or one an open story already links, is refused and
nothing changes. --story reads the issue from that story's worktree, where the
issues it recorded are until it is accepted; the new story is made in wip/ as
always.`,
		Example: `  flai issue story I-0007
  flai issue story I-0007 --epic E-0002
  flai issue story I-0012 --story S-0198`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			repo, err := a.project()
			if err != nil {
				return err
			}
			is, err := issues.Get(issues.RepoFor(repo, story), args[0])
			if err != nil {
				return err
			}
			if is.Status != "open" {
				return fmt.Errorf("%s is %s, so no story was made for it; reopen it by editing its status, or record a new issue", is.ID, is.Status)
			}
			items, err := repo.List(false)
			if err != nil {
				return err
			}
			if id := issues.LinkedBy(is, items); id != "" {
				return fmt.Errorf("%s is already linked by open story %s, so no story was made for it; work it in %s, or cancel %s first", is.ID, id, id, id)
			}
			draft := issues.ForStory(is)
			res, err := itemnew.Create(repo, a.runner, itemnew.Options{New: workitem.NewOptions{
				Type: workitem.Story, Title: draft.Title, Nature: draft.Nature, Parent: epic,
				Owner: a.author(), Body: draft.Body, Now: a.now(),
			}})
			if refusal, ok := a.refusedADR(err); ok {
				return refusal
			}
			if err != nil {
				return fmt.Errorf("making a story for %s: %w", is.ID, err)
			}
			if a.jsonOut {
				return a.printJSON(map[string]string{"id": res.Item.ID, "title": res.Item.Title, "nature": res.Item.Nature, "path": res.Path, "issue": is.ID})
			}
			fmt.Fprintf(a.out, "%s %s\n  %s\n", res.Item.ID, res.Item.Title, res.Path)
			return nil
		},
	}
	c.Flags().StringVar(&epic, "epic", "", "parent epic ID (optional: a story need not belong to one)")
	c.Flags().StringVar(&story, "story", "", "read the issue from this story's worktree when it has one")
	return c
}
