package cmd

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// referenceTitle is the reference page's title and first heading.
const referenceTitle = "flai command reference"

func newReferenceCmd(a *app) *cobra.Command {
	var write, settings string
	c := &cobra.Command{
		Use:   "reference",
		Short: "Print the command reference as markdown, generated from this help",
		Long: `Walk the command tree and print every command that help lists, with its
usage, description, aliases, examples, and flags, as one markdown page. With
--write the page replaces the file only when the commands changed, so its
updated date moves only then. With --settings as well, the index of every
flag between the flag markers of that page is replaced, linked to the
reference, and the rest of the page is left as it is. Maintainers run it as
make flai-reference.`,
		Example: `  flai reference --write docs/users/flai-reference.md --settings docs/operators/settings.md`,
		Hidden:  true,
		Args:    cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if write == "" {
				if settings != "" {
					return errors.New("--settings needs --write: the flag index links to the reference it writes")
				}
				_, err := fmt.Fprint(a.out, referencePage(a.now().Format("2006-01-02"), renderReference(cmd.Root())))
				return err
			}
			if err := a.writeReference(write, renderReference(cmd.Root())); err != nil {
				return err
			}
			if settings == "" {
				return nil
			}
			link, err := filepath.Rel(filepath.Dir(settings), write)
			if err != nil {
				return fmt.Errorf("link the flag index to the reference: %w", err)
			}
			return a.writeFlagIndex(settings, renderFlagIndex(cmd.Root(), filepath.ToSlash(link)))
		},
	}
	c.Flags().StringVar(&write, "write", "", "file to write the page to, left alone when only the date would change")
	c.Flags().StringVar(&settings, "settings", "", "page whose flag index to replace between its flag markers, left alone when it is current")
	return c
}

// writeReference replaces the reference at path when its body changed.
func (a *app) writeReference(path, body string) error {
	old, err := os.ReadFile(path)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("read the reference to compare: %w", err)
	}
	if err == nil && referenceBody(string(old)) == body {
		fmt.Fprintf(a.out, "%s is up to date\n", path)
		return nil
	}
	if err := os.WriteFile(path, []byte(referencePage(a.now().Format("2006-01-02"), body)), 0o644); err != nil {
		return fmt.Errorf("write the reference: %w", err)
	}
	fmt.Fprintf(a.out, "wrote %s\n", path)
	return nil
}

// referencePage is the reference with its front matter.
func referencePage(updated, body string) string {
	return fmt.Sprintf("---\ntitle: %s\nupdated: %s\nstatus: active\n---\n%s", referenceTitle, updated, body)
}

// referenceBody is a reference page without its front matter.
func referenceBody(page string) string {
	rest, ok := strings.CutPrefix(page, "---\n")
	if !ok {
		return page
	}
	if _, body, ok := strings.Cut(rest, "\n---\n"); ok {
		return body
	}
	return page
}

// renderReference renders every available command under root as markdown,
// in the order help lists them, below a table of the top-level commands.
func renderReference(root *cobra.Command) string {
	root.InitDefaultHelpCmd()
	root.InitDefaultCompletionCmd()
	var b bytes.Buffer
	fmt.Fprintf(&b, "\n<!-- Generated by flai reference from the command help. Edit the help in flai/cmd, then run make flai-reference. -->\n\n")
	fmt.Fprintf(&b, "# %s\n\n", referenceTitle)
	fmt.Fprintf(&b, "Every command, subcommand, and flag, as `%s --help` prints them. The guide, with how the commands fit together, is [flai.md](flai.md).\n\n", root.Name())
	b.WriteString("| Command | What it does |\n|---------|--------------|\n")
	for _, c := range availableCommands(root) {
		fmt.Fprintf(&b, "| [%s](#%s) | %s |\n", c.Name(), anchor(c.CommandPath()), escapeCell(c.Short))
	}
	renderCommand(&b, root, 2)
	return b.String()
}

// availableCommands are the subcommands help lists: not hidden, deprecated,
// or the help command.
func availableCommands(c *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	for _, sub := range c.Commands() {
		if sub.IsAvailableCommand() {
			out = append(out, sub)
		}
	}
	return out
}

func renderCommand(b *bytes.Buffer, c *cobra.Command, level int) {
	fmt.Fprintf(b, "\n%s %s\n\n", strings.Repeat("#", min(level, 6)), c.CommandPath())
	if c.Short != "" {
		fmt.Fprintf(b, "%s.\n\n", strings.TrimSuffix(escapeProse(c.Short), "."))
	}
	if c.Runnable() {
		fmt.Fprintf(b, "```text\n%s\n```\n\n", c.UseLine())
	}
	if c.Long != "" {
		renderLong(b, c.Long)
	}
	if len(c.Aliases) > 0 {
		fmt.Fprintf(b, "Aliases: `%s`.\n\n", strings.Join(c.Aliases, "`, `"))
	}
	if c.Example != "" {
		fmt.Fprintf(b, "Examples:\n\n```bash\n%s\n```\n\n", dedent(c.Example))
	}
	if !c.HasParent() {
		renderFlags(b, "Global flags, accepted by every command:", c.PersistentFlags())
	} else {
		renderFlags(b, "Flags:", c.LocalFlags())
		renderFlags(b, fmt.Sprintf("Flags from `%s`:", c.Parent().CommandPath()), inheritedBelowRoot(c))
	}
	if subs := availableCommands(c); len(subs) > 0 {
		b.WriteString("Subcommands:\n\n")
		for _, sub := range subs {
			fmt.Fprintf(b, "- [%s](#%s): %s\n", sub.Name(), anchor(sub.CommandPath()), escapeProse(sub.Short))
		}
		for _, sub := range subs {
			renderCommand(b, sub, level+1)
		}
	}
	trimTrailingBlank(b)
}

// inheritedBelowRoot are the persistent flags a command gets from a parent
// other than the root; the root's global flags are listed once, at the top.
func inheritedBelowRoot(c *cobra.Command) *pflag.FlagSet {
	global := c.Root().PersistentFlags()
	set := pflag.NewFlagSet(c.Name(), pflag.ContinueOnError)
	c.InheritedFlags().VisitAll(func(f *pflag.Flag) {
		if global.Lookup(f.Name) == nil {
			set.AddFlag(f)
		}
	})
	return set
}

func renderFlags(b *bytes.Buffer, title string, fs *pflag.FlagSet) {
	var rows []string
	fs.VisitAll(func(f *pflag.Flag) {
		if f.Hidden || f.Name == "help" {
			return
		}
		name := "`--" + f.Name + "`"
		if f.Shorthand != "" {
			name = "`-" + f.Shorthand + "`, " + name
		}
		kind, usage := pflag.UnquoteUsage(f)
		if kind != "" {
			name += " " + kind
		}
		usage = escapeCell(usage)
		if d := flagDefault(f); d != "" {
			usage += " (default `" + d + "`)"
		}
		if f.Deprecated != "" {
			usage += " Deprecated: " + escapeCell(f.Deprecated)
		}
		rows = append(rows, fmt.Sprintf("| %s | %s |", name, usage))
	})
	if len(rows) == 0 {
		return
	}
	fmt.Fprintf(b, "%s\n\n| Flag | Meaning |\n|------|---------|\n%s\n\n", title, strings.Join(rows, "\n"))
}

// flagDefault is the default help would print, or "" for a zero value.
func flagDefault(f *pflag.Flag) string {
	switch f.DefValue {
	case "", "false", "0", "[]", "0s":
		return ""
	}
	return f.DefValue
}

// renderLong writes a command's long help: paragraphs of wrapped prose are
// joined into one line each, and a paragraph with indented lines, a table or
// an example, is kept as it stands in a text block.
func renderLong(b *bytes.Buffer, long string) {
	for para := range strings.SplitSeq(strings.TrimSpace(dedent(long)), "\n\n") {
		lines := strings.Split(strings.Trim(para, "\n"), "\n")
		switch {
		case anyIndented(lines):
			block := strings.ReplaceAll(dedent(strings.Join(lines, "\n")), "\t", "    ")
			fmt.Fprintf(b, "```text\n%s\n```\n\n", block)
		case isList(lines):
			for _, l := range lines {
				b.WriteString(escapeProse(l) + "\n")
			}
			b.WriteString("\n")
		default:
			// A leading # is a label in help (cobra's "#### Linux:"), not a heading.
			text := strings.TrimLeft(strings.Join(lines, " "), "# ")
			b.WriteString(escapeProse(text) + "\n\n")
		}
	}
}

func anyIndented(lines []string) bool {
	for _, l := range lines {
		if strings.HasPrefix(l, " ") || strings.HasPrefix(l, "\t") {
			return true
		}
	}
	return false
}

func isList(lines []string) bool {
	for _, l := range lines {
		if strings.HasPrefix(l, "- ") {
			return true
		}
	}
	return false
}

// dedent removes the indentation every non-blank line shares.
func dedent(s string) string {
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	common := -1
	for _, l := range lines {
		if strings.TrimSpace(l) == "" {
			continue
		}
		n := len(l) - len(strings.TrimLeft(l, " \t"))
		if common < 0 || n < common {
			common = n
		}
	}
	for i, l := range lines {
		if len(l) >= common && common > 0 {
			lines[i] = l[common:]
		}
	}
	return strings.Join(lines, "\n")
}

// escapeProse keeps help text from being read as markdown or HTML: angle
// brackets would vanish as tags, and * or _ could start emphasis.
func escapeProse(s string) string {
	return strings.NewReplacer(`<`, `&lt;`, `>`, `&gt;`, `*`, `\*`, `_`, `\_`).Replace(s)
}

// escapeCell is escapeProse for a table cell, where | ends the cell.
func escapeCell(s string) string {
	return strings.ReplaceAll(escapeProse(strings.ReplaceAll(s, "\n", " ")), "|", `\|`)
}

// anchor is the heading ID GitHub and the dashboard give a command path.
func anchor(path string) string {
	return strings.ReplaceAll(strings.ToLower(path), " ", "-")
}

func trimTrailingBlank(b *bytes.Buffer) {
	for bytes.HasSuffix(b.Bytes(), []byte("\n\n")) {
		b.Truncate(b.Len() - 1)
	}
}
