package cmd

import (
	"bytes"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// The flag index sits between these two lines of the page it is written into.
const (
	flagIndexBegin = "<!-- flags:begin: generated by flai reference from the command help; run make flai-reference -->"
	flagIndexEnd   = "<!-- flags:end -->"
)

// renderFlagIndex is a table of every flag of every available command, one
// row per flag, each naming the commands that take it, linked to their
// section of the reference at link. A global flag is taken by every command.
func renderFlagIndex(root *cobra.Command, link string) string {
	root.InitDefaultHelpCmd()
	root.InitDefaultCompletionCmd()
	takers := map[string][]string{}
	add := func(fs *pflag.FlagSet, taker string) {
		fs.VisitAll(func(f *pflag.Flag) {
			if f.Hidden || f.Name == "help" {
				return
			}
			name := "`--" + f.Name + "`"
			if f.Shorthand != "" {
				name = "`-" + f.Shorthand + "`, " + name
			}
			takers[name] = append(takers[name], taker)
		})
	}
	add(root.PersistentFlags(), fmt.Sprintf("every command ([global flags](%s#%s))", link, anchor(root.CommandPath())))
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		for _, sub := range availableCommands(c) {
			add(sub.LocalFlags(), fmt.Sprintf("[%s](%s#%s)", sub.CommandPath(), link, anchor(sub.CommandPath())))
			walk(sub)
		}
	}
	walk(root)
	names := make([]string, 0, len(takers))
	for n := range takers {
		names = append(names, n)
	}
	sort.Slice(names, func(i, j int) bool { return flagSortKey(names[i]) < flagSortKey(names[j]) })
	var b bytes.Buffer
	b.WriteString("| Flag | Taken by |\n|------|----------|\n")
	for _, n := range names {
		fmt.Fprintf(&b, "| %s | %s |\n", n, strings.Join(takers[n], ", "))
	}
	return b.String()
}

// flagSortKey orders flags by long name, then without a shorthand first.
func flagSortKey(name string) string {
	name = strings.ReplaceAll(name, "`", "")
	if short, long, ok := strings.Cut(name, ", "); ok {
		return long + " " + short
	}
	return name
}

// updatedLine is a page's front matter date.
var updatedLine = regexp.MustCompile(`(?m)^updated: .*$`)

// writeFlagIndex replaces what is between the flag markers of the page at
// path with index, and its updated date, when the index changed.
func (a *app) writeFlagIndex(path, index string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read the page for the flag index: %w", err)
	}
	head, rest, ok := strings.Cut(string(data), flagIndexBegin+"\n")
	current, tail, ok2 := strings.Cut(rest, flagIndexEnd)
	if !ok || !ok2 {
		return fmt.Errorf("%s has no flag markers: put a line %q and, below it, a line %q where the index goes", path, flagIndexBegin, flagIndexEnd)
	}
	if current == index {
		fmt.Fprintf(a.out, "%s is up to date\n", path)
		return nil
	}
	if fm, body, ok := strings.Cut(head, "\n---\n"); ok {
		head = updatedLine.ReplaceAllString(fm, "updated: "+a.now().Format("2006-01-02")) + "\n---\n" + body
	}
	if err := os.WriteFile(path, []byte(head+flagIndexBegin+"\n"+index+flagIndexEnd+tail), 0o644); err != nil {
		return fmt.Errorf("write the flag index: %w", err)
	}
	fmt.Fprintf(a.out, "wrote the flag index into %s\n", path)
	return nil
}
